title: Avinash "Avi" Karn, PhD
description: Quantitative Geneticist & Computational Biologist
google_analytics: UA-123359651-1
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
