title: Shaun Jackman
description: PhD Candidate Bioinformatics, BASc (First Class Hons.) Computer Engineering
google_analytics: UA-2437900-4
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
