title: Avinash "Avi" Karn, PhD [http://AviKarn.com]
description: Quantitative Geneticist & Computational Biologist
google_analytics: UA-123359651-1
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
  
github:
  repository_url: http://AviKarn.com
  forkme_banner: "Webpage"
